spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxxxxx:3306/framework?useUnicode=true&characterEncoding=utf-8
    username: xxxxxxxx
    password: xxxxxxxx
mybatis:
  mapper-locations: classpath:sql-mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true